### ISSUE TITLE
Strange sense amp in SRAM

### ISSUE THREAD

**Issue by ogamespec** [msinger/gbreveng#4]
I found that the Sense Amp, which is just above the Column Mux for some reason works “in reverse” - it amplifies the value from the data bus instead of the cell. What do you think about it?

![image](https://github.com/user-attachments/assets/4bc57056-0128-4a87-b364-fb4f8b116fab)

**Comment by msinger** [comment]
I'm not an expert in SRAM terminology. :)
I think it is not the sense amp. I think the sense amps are the ones at the top in your picture, because they amplify the value read from the cell. I don't know what the "reverse sense amps" are typically called, but you need a strong driver to flip the value in the cells when writing. And those strong drivers need to drive the value through the column muxers at the bottom, so they need to be very big too.

**Comment by msinger** [comment]
They just call it write driver:
http://ce-publications.et.tudelft.nl/publications/1521_bti_analysis_of_sram_write_driver.pdf

**Comment by ogamespec** [comment]
So there is no canonical Sense Amp in the circuit?

![image](https://github.com/user-attachments/assets/fa9b6adb-d629-4c97-8075-28989750aa9d)

**Comment by msinger** [comment]
I'm confused about the picture. Is it a 5T SRAM cell?

If you look in my schematic http://iceboy.a-singer.de/doc/dmg_cells.html#sram (you have to scroll down a bit), I think transistors P11, N21, P20 and N30 are the ones that do the sensing, so they would be called the sense amps. Their gates are where the bit lines end, coming from the column multiplexers. They are also part of a NOR-latch, together with P10, N20, P21 and N31.

**Comment by msinger** [comment]
Ah, okay, sorry, I understand. It's a picture of a sense amplifier. I think they don't need a circuit like this, because they use dynamic logic. Since the bit lines go through the column multiplexer, which consists of only NMOS transistors, the bit lines can only drive low states. So in your sense amplifier circuit, M3 and M4 are driven directly by the bit lines, and M1 and M2 provide the complementary, based on the output of M3 and M4. In the Game Boy, they provide the complementary by precharging, using transistors P8 and P9.
I think in a standard SRAM chip, you don't want dynamic logic, because you would need a clock for controlling that, so they use the circuit you provided. In the Game Boy, they have the clock anyway, so maybe it's simpler to implement using precharging.

**Comment by msinger** [comment]
After sleeping over it, of course what I wrote makes no sense. You need to precharge the bit lines anyway. I don't know why they implemented the sensing differently.

**Comment by ogamespec** [comment]
Thanks, yes I also think that because of precharge they don't need to add Sense Amp and even the output nor latch doesn't play a “sense” role here, it's just used as a flip/flop to keep the bus going (“bus keeper”).
Why I asked all this - you have “sense amp” in your Cells Reference, so I just wanted to clarify.
I think we can close :-)

**Comment by ogamespec** [comment]
My part of the SRAM elements research:
https://github.com/ogamespec/dmgcpu/blob/main/wiki/soc/hram.md

It's not finished, but the other elements have already been explored by you and are pretty simple and of little interest (Cell Array, Row Decoder).
